### ISSUE TITLE
Bot showing error in uploading telegram files

### ISSUE THREAD

**Issue by Rahul-Tyagi12** [magneto261290/magneto-python-aria#11]
Sir how are u,here i want to post a little issue about your awesome bot.
Bot working fine but while uploading telegram files to gdrive it returns (@username your download has been stopped due to: No document in the replied message).but i replied to a telegram file.
Can u please help me to fix it,kindly look at my issue sir.

![Screenshot_20200724-220705_Telegram (1)](https://user-images.githubusercontent.com/61530246/88414284-3997f700-cdfa-11ea-9d59-66756ba9e6bf.jpg)

**Comment by magneto261290** [comment]
1. While generating string session, use bot token (don't use mobile number) for generating string session.
2. Telegram file mirroring works in group, not in personal chat.


You can contact me on telegram for any further discussion @The_magneto (https://t.me/The_magmeto)
