### ISSUE TITLE
Getting error while adding SA in Team Drive

### ISSUE THREAD

**Issue by doloresjose** [magneto261290/magneto-python-aria#12]
Getting this error while adding SA in Team Drive
![Capture](https://user-images.githubusercontent.com/62073313/88430724-92758880-ce16-11ea-8c76-ab51adfbc52c.PNG)

and also tell me what does "SharedTeamDriveSrcID" this means

also i tried to deploy it without SA to heroku everything went fine and the deployment was successful but when tried to give command to the bot it did not respond and gave this error, and as it states "env variable is missing"but i checked many times in config.env file and everything was filled correctly, please help me with this
![Capture](https://user-images.githubusercontent.com/62073313/88434046-f3a05a80-ce1c-11ea-90f9-d6027c6994b1.PNG)

**Comment by im-asf** [comment]
i also got this locale error, any fixes?

**Comment by enjeyisback** [comment]
you guys can ignore the locale error. but fir ENV variable missing. you may have missed to put some info in config file. like when you tried with SA account. you may had put True at SA account in config. but when trying without SA you should remove that True as well.

**Comment by immoIT** [comment]
![IMG_20200830_220941](https://user-images.githubusercontent.com/66837604/91664900-c461c500-eb0f-11ea-8efc-4336c9380c2c.jpg)
what its means how fix it torrent folder created but file not uploaded

**Comment by magneto261290** [comment]
> ![IMG_20200830_220941](https://user-images.githubusercontent.com/66837604/91664900-c461c500-eb0f-11ea-8efc-4336c9380c2c.jpg)
> what its means how fix it torrent folder created but file not uploaded

If you are uploading to Teamdrive, set IS_TEAM_DRIVE to True. Don't leave that value blank.

**Comment by anasty17** [comment]
@doloresjose pip3 install progress or pip3 install -r requirements.txt
