### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by im-asf** [magneto261290/magneto-python-aria#16]
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2020-08-12 06:17:04,221 - bot - ERROR - One or more env variables missing! Exiting now

This error occurs while running docker in the last step

**Comment by magneto261290** [comment]
It's not locale error, that is just a warning.
The error is that you have not filled all reauired config values.

**Comment by im-asf** [comment]
I have filled everything except telegraph api as i dont have telegraph

**Comment by magneto261290** [comment]
> I have filled everything except telegraph api as i dont have telegraph

You don't need any additional thing for using telegraph, just run `python generate_telegraph_token.py` and enter your telegram username. you will get telegraph token. It's so easy man.

**Comment by im-asf** [comment]
I did still same error

**Comment by im-asf** [comment]
Can u pm me in telegram pls.. My id im_asf
