### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by cloudoftg** [magneto261290/magneto-python-aria#17]
Will you ever add heroku support. When i tried to deploy it using CLI heroku it works but config file is missing?

**Comment by askfriends** [comment]
that would be great, hope to have it soon.
and plz add zipping feature too to compress files/folders from td

**Comment by magneto261290** [comment]
Never going to add heroku support. and don't wanna talk about that.bcoz Heroku doesn't support p2p connection. Heroku might ban this repo.

**Comment by magneto261290** [comment]
> that would be great, hope to have it soon.
> and plz add zipping feature too to compress files/folders from td

download from gdrive supposed to be added in staging 5.0 of official repo. So i will wait for that, but if i get code early, i will surely implement that.
