### ISSUE TITLE
stuck at archiving downloading

### ISSUE THREAD

**Issue by sapthesh** [magneto261290/magneto-python-aria#18]
When ever I add a magnet link or direct link the bot downloads the file but the progress is stuck at Downloading or Archiving.

The file is not uploading to drive or shared drive. 

Please let me know what might be the issue. 

Below are the log which shows in the log file

```
2020-08-17 10:16:56,258 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 0.json service account
```

Nothing goes beyond that..

**Comment by magneto261290** [comment]
It seems that you made some mistake while setting up Service accounts. maybe you didn't rename SAs to 0.json, 1.json, 2.json..... etc.

**Comment by sapthesh** [comment]
It's showing in the accounts folder,
0.json
1.json
So on..

**Comment by magneto261290** [comment]
Then make sure your service accounts have Content manager access.
I am closing this issue. contact me on telegram [@The_magneto](https://t.me/The_magneto)
