### ISSUE TITLE
MAX_CONCURRENT_DOWNLOADS in config.env

### ISSUE THREAD

**Issue by UsamaKarim** [magneto261290/magneto-python-aria#20]
Hi, Dev Singh Rajput
Can you please implement MAX_CONCURRENT_DOWNLOADS in config.env so if I need to change it, I can easily change it in config vars and revert it. I want this implementation because Some sites do not support downloading more than one file at a time so it will be helpful if I can change vars quickly rather than changing it every time in aria.sh.

I hope I make you understand what I want.

Thanks

**Comment by magneto261290** [comment]
you can change this value is aria.sh as quick as in config.env

how you are saying that you can change quickly if i put this option in config vars??

**Comment by UsamaKarim** [comment]
I deployed bot on heroku. Rather than deploying again after changing value in aria.sh, I can change value in heroku bars instantly

**Comment by magneto261290** [comment]
Have you done this?

**Comment by UsamaKarim** [comment]
No, you didn't responded, that's why I closed it

**Comment by magneto261290** [comment]
> No, you didn't responded, that's why I closed it

Plz contact me on telegram. my username is [@The_magneto](https://t.me/The_magneto)
