### ISSUE TITLE
Hotstar Video Format

### ISSUE THREAD

**Issue by jgo42** [magneto261290/magneto-python-aria#25]
Can u please change the default setting of hotstar video format to mkv from mp4

**Comment by magneto261290** [comment]
Youtube-dl set it automatically. First it tries to merge video and audio into mp4, if codec is vp9 or audio codes is opus, it will merge them into mkv format.

still if you want to merge all codec into mkv format add a new opt. in youtube_dl_download_helper.py

> 'merge_output_format': 'mkv'
