### ISSUE TITLE
Search Before mirroring 

### ISSUE THREAD

**Issue by Suyashjain05** [magneto261290/magneto-python-aria#26]
Hey there, please add a feature that would search for a torrent using it's info hash/name whichever way possible so that if someone mirrors a torrent that already exists so that the bot doesn't waste resources on a file which already exists.

**Comment by Kiran-web-star** [comment]
The feature Is already There Duplicate Mirror Set as False In Config.env

**Comment by Suyashjain05** [comment]
oh okay, sorry, thank you very much for the information
