### ISSUE TITLE
Searching Of sub-directories folders

### ISSUE THREAD

**Issue by Hemchand-King** [magneto261290/magneto-python-aria#28]
The bot is unable to search in sub-directories , The files in sub directories

**Comment by magneto261290** [comment]
Yes. it is unable bcoz google does not provide option to search in subdirectories using google drive API.
you can search in whole drive/teamdrive and it's subdirectories using google drive API but you can't search in a folder with it's sub-directories.

**Comment by Hemchand-King** [comment]
Is there any solution?
