### ISSUE TITLE
Direct Links Error

### ISSUE THREAD

**Issue by mehlam619** [magneto261290/magneto-python-aria#29]
Direct links from Mediafire and Zippyshare aint working.

**Comment by magneto261290** [comment]
Bot automatically generates direct link of mediafire, zippyshare and some other sites. So use page link (not direct link) of mediafire. Your file will be mirrored.

**Comment by mehlam619** [comment]
> Bot automatically generates direct link of mediafire, zippyshare and some other sites. So use page link (not direct link) of mediafire. Your file will be mirrored.

zippyshare still isnt working.
