### ISSUE TITLE
"#" is causing trouble

### ISSUE THREAD

**Issue by ghost** [magneto261290/magneto-python-aria#37]
this is file: https://github.com/magneto261290/magneto-python-aria/blob/master/bot/modules/mirror.py
line: 154 - 155

siurl = requests.get('https://{}/api?api={}&url={}&format=text'.format(SHORTENER, SHORTENER_API, share_url)).text
                    buttons.buildbutton("💥Index Link💥", siurl)

when i try to download this: https://turkseed.com/details.php?id=33726

its giving:
ERROR - wrong url host

i think its because of file name. others is downloading without any error.

this filename: "Turkseed.com / HD / Clara 2018 TR 1080p WebDL #turkseed"
probably "#" is causing trouble.
how can i fix this?

**Comment by magneto261290** [comment]
I don't think that there any problem in downloading.
Problem is in making shortner link after uploading file. Don't fill SHORTNER and SHORTNER_API in config.env if you aren't using shortner

**Comment by vergaten** [comment]
> 
> 
> I don't think that there any problem in downloading.
> Problem is in making shortner link after uploading file. Don't fill SHORTNER and SHORTNER_API in config.env if you aren't using shortner

yes. the problem is when uploading.
i'm trying now encode the url, and send to url shortner.
i'll write here if it success.
