### ISSUE TITLE
Crypto mining detected?

### ISSUE THREAD

**Issue by iykoou** [magneto261290/magneto-python-aria#39]
My friend used this repo and this happened.
Have any idea?

![crypto](https://user-images.githubusercontent.com/69583226/96243192-94db1f00-0fce-11eb-9d16-1045576f5ff9.jpg)

![IMG_20201016_172901_233](https://user-images.githubusercontent.com/69583226/96248017-1afa6400-0fd5-11eb-9082-75bd0b5b1f4b.PNG)

**Comment by magneto261290** [comment]
Bot source code is open and you can see that there is not any script/coding in bot for crypto mining. You might be using other apps or maybe you browsed some websites that uses javascripts to mine cryptocurrencies in background(without letting you know what are they doing).
