### ISSUE TITLE
HDD NAS SERVER

### ISSUE THREAD

**Issue by arjun4414** [magneto261290/magneto-python-aria#44]
I have my HDD NAS and g drive .
I want files on both drives can you help me in this ? It's on the same network the bot and HDD NAS SERVER. I DON'T WANT TO DELETE FILES FROM MY STORAGE DRIVE .
PLEASE REPLY ME WITH A SOLUTION TO MY QUESTION AND HELP ME WITH THIS! 
THANKS

**Comment by magneto261290** [comment]
Sorry for late response.
For faster reply you can contact me on Telegram. My username is @The_magneto.

You want to say that you don't want to delete files from your server storage after uploading complete???

if yes then delete line no. 170,171,172,173 from bot/modules/mirror.py file.
