### ISSUE TITLE
YouTube Total Downloaded Size Is Broken After Today's Update

### ISSUE THREAD

**Issue by ravidkumar** [magneto261290/magneto-python-aria#47]
I tried downloading videos from youtube and discovered it downloaded fine but shows 0B on the end message.. Fix it thanks

**Comment by magneto261290** [comment]
I am working on it. will be fixed soon.....

**Comment by magneto261290** [comment]
One more think i want to tell you that size in downloading status of ytdl can't be fixed. I will fix size in uploading status and after upload message.

**Comment by RomanGoddess** [comment]
Thanks

**Comment by ravidkumar** [comment]
Thanks

**Comment by magneto261290** [comment]
Fixed bro..

Now closing this PR
