### ISSUE TITLE
Request for bot

### ISSUE THREAD

**Issue by Rahul-Tyagi12** [magneto261290/magneto-python-aria#5]
Sir i am using your excellent bot ,and i request u to add /delete and /rename command for bot admin only so we can modify files without touching google drive on browser

I will be highly thankfull to u sir. i hope u will look at my request soon.

**Comment by magneto261290** [comment]
/del command is already available for bot owner only.

**Comment by Rahul-Tyagi12** [comment]
Ohh ok sir thanks for your valuable reply,i was using /delete instead of
/del.
Thanks sir
