### ISSUE TITLE
Heroku suspend: Process exited with status 143

### ISSUE THREAD

**Issue by OryWareKyrie** [magneto261290/magneto-python-aria#53]
> 2020-11-15T21:04:30.607867+00:00 heroku[worker.1]: State changed from up to down
2020-11-15T21:04:32.154881+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2020-11-15T21:04:32.271344+00:00 heroku[worker.1]: Process exited with status 143

**Comment by KenHV** [comment]
Heroku suspended your app/account for abuse. Not an issue with the bot itself.

**Comment by yashptel** [comment]
This and every other bot except the original lzzy12/python-aria-mirror-bot gets suspended for me instantly. Are there any solutions?

**Comment by KenHV** [comment]
> This and every other bot except the original lzzy12/python-aria-mirror-bot gets suspended for me instantly. Are there any solutions?

You can host it locally or find other hosting services.
