### ISSUE TITLE
List command is not working

### ISSUE THREAD

**Issue by ikssas35** [magneto261290/magneto-python-aria#6]
msg, button = gdrive.drive_list(search)

2020-07-22T06:03:21.482769+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 476, in drive_list

2020-07-22T06:03:21.482769+00:00 app[worker.1]:     buttons = button_builder.ButtonMaker()

2020-07-22T06:03:21.482770+00:00 app[worker.1]: NameError: name 'button_builder' is not defined

**Comment by TheFierceWarrior** [comment]
import issue check "bot/helper/mirror_utils/upload_utils/gdriveTools.py"

**Comment by TheFierceWarrior** [comment]
and try to solve by yourself

**Comment by ikssas35** [comment]
Yes, i have fixed by myself.. 

From "magneto-python-aria/bot/helper/mirror_utils/upload_utils/gdriveTools.py"
Changed "buttons = button_**builder**.ButtonMaker()" to "buttons = button_**build**.ButtonMaker()".. 
(Line 476)

Now everything is fine. 

Thanks for your response..

**Comment by TheFierceWarrior** [comment]
good

**Comment by ikssas35** [comment]
Please re-update the list module with the fixed code. (Perhaps, after my comment, you have rolled back to the old list module).   
Thanks ☺

**Comment by magneto261290** [comment]
Now Fixed.
Note :- use https:// in your index link in config.env, otherwise /list module will not hyperlink your Index url

**Comment by ikssas35** [comment]
Thanks bro ☺
