### ISSUE TITLE
SHORTENER ERRORS

### ISSUE THREAD

**Issue by nullbytes0** [magneto261290/magneto-python-aria#60]
![Screenshot_20201227-140151_Chrome](https://user-images.githubusercontent.com/49795299/103164951-976ab800-484c-11eb-9678-4edfe23b49a2.jpg)

SHORTENER = "https://shrinke.me/demoonly"
SHORTENER_API = "cb504645f5fblabLablablablablablablablablabalabla"
Iput that but got error see the screen shot please
And help me what is the proper.

**Comment by magneto261290** [comment]
Where did you get shrinke.me api???

**Comment by nullbytes0** [comment]
> Where did you get shrinke.me api???

This api is an example only > SHORTENER_API = "cb504645f5fblabLablablablablablablablablabalabla"

But a get the real api in TOOLS > DEVELOPERS API .

and put in SHORTENER_API =""

**Comment by magneto261290** [comment]
I know it is an example only...
give me link for signup on shrinke.me and getting api key

**Comment by nullbytes0** [comment]
Please can you give me an example sir?

**Comment by magneto261290** [comment]
I just want to know how did you get api key.
bcoz i did not find any option on shrinke.me to get api key

**Comment by nullbytes0** [comment]
> I just want to know how did you get api key.
> bcoz i did not find any option on shrinke.me to get api key

https://shrinkme.io/member/tools/api

**Comment by magneto261290** [comment]
> > I just want to know how did you get api key.
> > bcoz i did not find any option on shrinke.me to get api key
> 
> https://shrinkme.io/member/tools/api

oh bro

It's shrinkme.io not shrinke.me
so put value in config.env like this
SHORTENER = "shrinkme.io"
SHORTENER_API = "blablablablablablablablablablablabla"

**Comment by magneto261290** [comment]
Don't use http:// or https:// in SHORTENER, it will be added automatically

**Comment by nullbytes0** [comment]
> Don't use http:// or https:// in SHORTENER, it will be added automatically

Okay sir ill try thank you!
