### ISSUE TITLE
Mediafire Mirror stopped due to: SSL/TLS handshake failure

### ISSUE THREAD

**Issue by abdulkader00** [magneto261290/magneto-python-aria#75]
When I put a mediafire link to mirror its says this message

 your download has been stopped due to: SSL/TLS handshake failure:  `not signed by known authorities or invalid' `expired'

Any solution?
![IMG_20210130_151943](https://user-images.githubusercontent.com/75881574/106352599-a393da80-630e-11eb-9104-dc99e638de79.jpg)

**Comment by adisubagja** [comment]
@abdulkader00 Hmm i think this issue from mediafire / zippyshare ur must change https to http

example https://mediafire.com/vlabla to http://mediafire.com/vlavla u can try urself

**Comment by abdulkader00** [comment]
It worked. Thanks @adisubagja Bro
