### ISSUE TITLE
Telegram mirror cannot detect duplicate mirror

### ISSUE THREAD

**Issue by yasirarism** [magneto261290/magneto-python-aria#77]
I has set stop duplicate mirror, but when use mirror from telegram file it does not work. Only work with link only.

**Comment by FristyFlakes** [comment]
Sometimes fails with direct links. Sometimes works

**Comment by magneto261290** [comment]
@yasirarism bcoz that is implemented in aria2
so stop duplicate mirror will not work for ytdl, mega, TG file mirror
