### ISSUE TITLE
Telegraph issue

### ISSUE THREAD

**Issue by advik-afk** [magneto261290/magneto-python-aria#9]
when i put cms then it shows this error

Traceback (most recent call last):
  File "generate_telegraph_token.py", line 1, in <module>
    from telegraph import Telegraph
ModuleNotFoundError: No module named 'telegraph'

**Comment by magneto261290** [comment]
You have not installed all the requirements.
run this command 
`pip3 install -r requirements.txt`

or you can install only telegraph
`pip3 install telegraph`
